const animation = {
  fadeIn: 'fadeIn',
  zoomIn: 'zoomIn',
  zoomOut: 'zoomOut',
  bounce: 'bounce',
  flash: 'flash',
  jello: 'jello',
  pulse: 'pulse',
  rotate: 'rotate',
  rubberBand: 'rubberBand',
  shake: 'shake',
  swing: 'swing',
  tada: 'tada',
  wobble: 'wobble',
  bounceIn: 'bounceIn',
  bounceInDown: 'bounceInDown',
  bounceInUp: 'bounceInUp',
  bounceInLeft: 'bounceInLeft',
  bounceInRight: 'bounceInRight',
  bounceOut: 'bounceOut',
  bounceOutDown: 'bounceOutDown',
  bounceOutUp: 'bounceOutUp',
  bounceOutLeft: 'bounceOutLeft',
  bounceOutRight: 'bounceOutRight',
  fadeInDown: 'fadeInDown',
  fadeInDownBig: 'fadeInDownBig',
  fadeInUp: 'fadeInUp',
  fadeInUpBig: 'fadeInUpBig',
  fadeInLeft: 'fadeInLeft',
  fadeInLeftBig: 'fadeInLeftBig',
  fadeInRight: 'fadeInRight',
  fadeInRightBig: 'fadeInRightBig',
  flipInX: 'flipInX',
  flipInY: 'flipInY',
  flipOutX: 'flipOutX',
  flipOutY: 'flipOutY',
  lightSpeedIn: 'lightSpeedIn',
  slideInDown: 'slideInDown',
  slideInUp: 'slideInUp',
  slideInLeft: 'slideInLeft',
  slideInRight: 'slideInRight',
  zoomInDown: 'zoomInDown',
  zoomInUp: 'zoomInUp',
  zoomInLeft: 'zoomInLeft',
  zoomInRight: 'zoomInRight',
};

export default animation;
