export const data = [
  {
    userId: 1,
    id: 1,
    title: 'Does he write an email',
    name: 'old school friends',
    profilePic: '',
    lastSeen: '10:36 PM',
    status: false,
    unseenMsg: 3,
    mute: false,
    lastCall: '(3) Today 18:26',
    adoCall: true,
    vdoCall: false,
    missed: true,
    received: false,
    phone:'+91-878-5531-51'
  },
  {
    userId: 2,
    id: 2,
    title: 'Finally I can finish it.',
    name: 'Kristin watston',
    profilePic: 'https://www.w3schools.com/howto/img_avatar2.png',
    lastSeen: '10:36 PM',
    status: true,
    unseenMsg: 1,
    lastCall: '12 min ago',
    adoCall: true,
    vdoCall: false,
    missed: true,
    received: false,
    phone:'+91-878-5531-51'
  },
  
  {
    userId: 3,
    id: 3,
    title: 'delectus aut autem',
    name: 'David',
    profilePic: '',
    lastSeen: '10:36 PM',
    status: false,
    unseenMsg: 2,
    mute: false,
    lastCall: 'Today 14:20',
    adoCall: false,
    vdoCall: true,
    missed: false,
    received: true,
    phone:'+91-878-5531-51'
  },
  {
    userId: 4,
    id: 4,
    title: 'Guess what am I',
    name: 'Katrin',
    profilePic: '',
    lastSeen: '10:36 PM',
    status: false,
    unseenMsg: 0,
    mute: true,
    lastCall: 'Yesterday 13:6',
    adoCall: true,
    vdoCall: false,
    missed: false,
    received: true,
    phone:'+91-878-5531-51'
  },
  {
    userId: 5,
    id: 5,
    title: 'I will walk later',
    name: 'Austin Joe',
    profilePic: '',
    lastSeen: '10:36 PM',
    status: false,
    unseenMsg: 0,
    mute: false,
    lastCall: 'Yesterday 14:00',
    adoCall: true,
    vdoCall: false,
    missed: true,
    received: false,
    phone:'+91-878-5531-51'
  },
  {
    userId: 6,
    id: 6,
    title: 'Do you wanna go on a ride with me.',
    name: 'Jenny',
    profilePic: '',
    lastSeen: '10:36 PM',
    status: true,
    unseenMsg: 0,
    mute: false,
    lastCall: 'Feb 25, 2022, 13:26',
    adoCall: false,
    vdoCall: true,
    missed: false,
    received: true,
    phone:'+91-878-5531-51'
  },
  {
    userId: 7,
    id: 7,
    title: 'Hey',
    name: 'Alisa',
    profilePic: '',
    lastSeen: '10:36 PM',
    status: false,
    unseenMsg: 0,
    mute: true,
  },
  {
    userId: 8,
    id: 8,
    title: 'I am at my place',
    name: 'Rockey',
    profilePic: '',
    lastSeen: '10:36 PM',
    status: true,
    unseenMsg: 0,
    mute: true,
  },
  {
    userId: 9,
    id: 9,
    title: 'Hi',
    name: 'Jhone watston',
    profilePic: '',
    lastSeen: '10:36 PM',
    status: false,
    unseenMsg: 0,
    mute: false,
  },
  {
    userId: 10,
    id: 10,
    title: 'Hi',
    name: 'KJS watston',
    profilePic: '',
    lastSeen: '10:36 PM',
    status: false,
    unseenMsg: 0,
    mute: false,
  },
];
