const colors = {
  primary: '#00FFE5',
  secondary: '#0078FF',
  warning: '#A6A6AA',
  success: '#002C6D',
  dark: '#000',
  light: '#fff',
  danger: '#CBCBD4',
  black :'#525252',
  green:'#00950F'
};

const size = {
  heading: 24,
  subheading: 20,
  mytitle: 18,
  title: 16,
  subtitle: 14,
  label: 12,
};

const family = {
  bold: 'Poppins-Bold',
  semibold: 'Poppins-SemiBold',
  regular: 'Poppins-Regular',
  medium: 'Poppins-Medium',
  light: 'Poppins-Light',
};

const images = {
  Splash: require('../images/Splash.png'),
  logo: require('../images/logo.png'),
  login: require('../images/Login.png'),
  otp: require('../images/OTP.png'),
  signup: require('../images/SignUp.png'),
  intro1: require('../images/Intro1.png'),
  intro2: require('../images/Intro2.png'),
  phone: require('../images/phone.png'),
  left: require('../images/left-arrow.png'),
  profilebg: require('../images/profilebg.png'),
  user: require('../images/user.png'),
  profile_icon: require('../images/profile_icon.png'),
  gender: require('../images/gender.png'),
  Dob: require('../images/Dob.png'),
  calender : require('../images/calender.png'),
  camera : require('../images/camera.png'),
  gra_camera : require('../images/gra_camera.png'),
  gallery : require('../images/gallery.png'),
  home_logo : require('../images/home_logo.png'),
  search : require('../images/icons_search.png'),
  menu : require('../images/menu.png'),
  check : require('../images/check.png'),
  avtar : require('../images/avatar.png'),
  mute : require('../images/mute.png'),
  call : require('../images/call.png'),
  video : require('../images/video.png'),
  received : require('../images/received.png'),
  missed : require('../images/missed.png'),
  outlinePhone : require('../images/outlinePhone.png'),
  outlineVdo : require('../images/outlineVdo.png'),
  smile : require('../images/smile.png'),
  keyboard : require('../images/keyboard.png'),
  attachment : require('../images/attachment.png'),
  send : require('../images/send.png'),
  mic : require('../images/mic.png'),
  outlinecamera : require('../images/outlinecamera.png'),
  close : require('../images/close.png'),
  edit_alt : require('../images/edit-alt.png'),
  account : require('../images/account.png'),
  chat : require('../images/chat.png'),
  help : require('../images/help.png'),
  logout : require('../images/logout.png'),
  notifications : require('../images/notifications.png'),
  security : require('../images/security.png'),
  arrow_right : require('../images/arrow-right.png'),
  arrow_down : require('../images/arrow-down.png'),
  arrow_up : require('../images/arrow-up.png'),
  right : require('../images/right-arrow.png'),
  users : require('../images/users-avatar.png'),
  photos : require('../images/photos.png'),
  circle_check : require('../images/circle-check.png'),
  links : require('../images/links.png'),
  share : require('../images/share.png'),
  block : require('../images/block.png'),
  bell : require('../images/bell.png'),
  report : require('../images/report.png'),
  intro_logo : require('../images/intro_logo.png'),
  audio : require('../images/audio.png'),
  location : require('../images/location.png'),
  contact : require('../images/contact.png'),
  file_image : require('../images/file-image.png'),
  document : require('../images/document.png'),
  camera_outline : require('../images/camera-outlined.png'),

  back_share :require('../images/back_share.png'),
  star :require('../images/star.png'),
  copy :require('../images/copy.png'),
  forward_share :require('../images/forward_share.png'),
  delete :require('../images/delete.png'),
  message : require('../images/message.png'),
  refresh : require('../images/refresh.png')
};

export {colors, images, size, family};
